/**
 * Per-seller paymentRules override the global admin defaults.
 * Fields:
 *   commissionRate  — platform fee % (overrides global slider)
 *   holdDays        — reserve hold in days after delivery
 *   refundWindowDays— customer return window in days
 *   minPayoutAmount — minimum AED balance before auto-payout triggers
 *   manualCapture   — require admin to manually capture payments
 *   autoPayout      — release payout automatically when all checks pass
 *   payoutMethod    — "bank" | "wallet" | "cod_hold"
 *   notes           — internal admin note
 */

export const shops = [
  {
    id: "shop-sweet-studio",
    name: "Sweet Studio",
    owner: "Lina Al Rashid",
    city: "Dubai",
    status: "Approved",
    fulfillmentRate: 97,
    disputeRate: 0.5,
    serviceRating: 4.9,
    payoutHoldDays: 3,
    commissionRate: 12,
    pendingBalance: 0,
    availableBalance: 0,
    holdBalance: 0,
    paidBalance: 0,
    avatar: "SS",
    story: "Artisan cakes, dessert boxes, and gift-ready perfume pairings made for luxury celebrations.",
    cover: "Luxury bespoke cakes and perfume gifts",
    category: "mixed",
    categories: ["perfume", "cake", "dessert", "gift_box"],
    paymentRules: {
      commissionRate:   12,
      holdDays:         3,
      refundWindowDays: 5,
      minPayoutAmount:  500,
      manualCapture:    false,
      autoPayout:       true,
      payoutMethod:     "bank",
      notes:            "Trusted cake seller. Expedited hold reduced from 5 to 3 days.",
    },
  },
  {
    id: "shop-la-patisserie",
    name: "La Pâtisserie",
    owner: "Nadia Karimi",
    city: "Abu Dhabi",
    status: "Approved",
    fulfillmentRate: 95,
    disputeRate: 0.7,
    serviceRating: 4.8,
    payoutHoldDays: 3,
    commissionRate: 11,
    pendingBalance: 0,
    availableBalance: 0,
    holdBalance: 0,
    paidBalance: 0,
    avatar: "LP",
    story: "French-inspired pastry and Arabic sweets, crafted for gifting and celebrations.",
    cover: "French pastry & Arabic sweets",
    category: "cakes",
    paymentRules: {
      commissionRate:   11,
      holdDays:         3,
      refundWindowDays: 5,
      minPayoutAmount:  400,
      manualCapture:    false,
      autoPayout:       true,
      payoutMethod:     "bank",
      notes:            "Premium tier — negotiated 11% commission. Strong track record.",
    },
  },
  {
    id: "shop-oud-lane",
    name: "Oud Lane",
    owner: "Mariam Al Noor",
    city: "Dubai",
    status: "Approved",
    fulfillmentRate: 96,
    disputeRate: 1.4,
    serviceRating: 4.7,
    payoutHoldDays: 5,
    commissionRate: 14,
    pendingBalance: 0,
    availableBalance: 0,
    holdBalance: 0,
    paidBalance: 0,
    avatar: "OL",
    story: "Small-batch oud and amber perfumes blended in Dubai.",
    cover: "Reserve oud blends",
    paymentRules: {
      commissionRate:   14,
      holdDays:         5,
      refundWindowDays: 7,
      minPayoutAmount:  1000,
      manualCapture:    false,
      autoPayout:       false,
      payoutMethod:     "bank",
      notes:            "High-value orders — manual payout review required above AED 3 000.",
    },
  },
  {
    id: "shop-rose-vault",
    name: "Rose Vault",
    owner: "Sana Hassan",
    city: "Sharjah",
    status: "Pending review",
    fulfillmentRate: 91,
    disputeRate: 2.1,
    serviceRating: 4.5,
    payoutHoldDays: 7,
    commissionRate: 13,
    pendingBalance: 0,
    availableBalance: 0,
    holdBalance: 0,
    paidBalance: 0,
    avatar: "RV",
    story: "Soft florals, rose oils, and modern gift-ready perfume.",
    cover: "Fresh floral atelier",
    paymentRules: {
      commissionRate:   13,
      holdDays:         7,
      refundWindowDays: 10,
      minPayoutAmount:  750,
      manualCapture:    true,
      autoPayout:       false,
      payoutMethod:     "bank",
      notes:            "New seller — pending verification. Manual capture on all orders until approved.",
    },
  },
  {
    id: "shop-citrus-atelier",
    name: "Citrus Atelier",
    owner: "Khalid Mansoor",
    city: "Abu Dhabi",
    status: "Approved",
    fulfillmentRate: 94,
    disputeRate: 0.8,
    serviceRating: 4.6,
    payoutHoldDays: 5,
    commissionRate: 12,
    pendingBalance: 0,
    availableBalance: 0,
    holdBalance: 0,
    paidBalance: 0,
    avatar: "CA",
    story: "Clean daily scents with citrus, tea, neroli, and cedar.",
    cover: "Fresh everyday fragrance",
    paymentRules: {
      commissionRate:   12,
      holdDays:         5,
      refundWindowDays: 7,
      minPayoutAmount:  600,
      manualCapture:    false,
      autoPayout:       true,
      payoutMethod:     "wallet",
      notes:            "Switched to wallet payout at seller request. No issues.",
    },
  },
  {
    id: "shop-musk-room",
    name: "Musk Room",
    owner: "Noura Yasin",
    city: "Ajman",
    status: "Approved",
    fulfillmentRate: 89,
    disputeRate: 2.8,
    serviceRating: 4.3,
    payoutHoldDays: 7,
    commissionRate: 15,
    pendingBalance: 0,
    availableBalance: 0,
    holdBalance: 0,
    paidBalance: 0,
    avatar: "MR",
    story: "Soft musk, skin scents, and quiet luxury perfumes.",
    cover: "Clean musk essentials",
    paymentRules: {
      commissionRate:   15,
      holdDays:         7,
      refundWindowDays: 10,
      minPayoutAmount:  800,
      manualCapture:    true,
      autoPayout:       false,
      payoutMethod:     "bank",
      notes:            "Elevated dispute rate — hold extended. Manual capture until Q3 review.",
    },
  },
];

export const customerProfiles = [
  {
    id: "cus-aisha",
    name: "Aisha K.",
    email: "aisha@example.com",
    phone: "+971 50 118 2401",
    city: "Dubai",
    status: "VIP",
    segment: "Luxury gifting",
    risk: "Low",
    orders: 8,
    lifetimeValue: 6240,
    avgOrderValue: 780,
    loyaltyPoints: 2480,
    lastOrderAt: "2026-05-29",
    preferredCategories: ["Oud", "Gift boxes", "Evening perfumes"],
    savedOccasions: ["Eid", "Anniversary"],
    favoriteShopIds: ["shop-oud-lane", "shop-sweet-studio"],
    openTickets: 0,
    notes: "Prefers evening delivery and premium gift wrapping.",
    tags: ["VIP", "Card payer", "Gift buyer"],
  },
  {
    id: "cus-omar",
    name: "Omar R.",
    email: "omar@example.com",
    phone: "+971 55 302 1940",
    city: "Abu Dhabi",
    status: "Active",
    segment: "Daily fragrance",
    risk: "Low",
    orders: 5,
    lifetimeValue: 2140,
    avgOrderValue: 428,
    loyaltyPoints: 840,
    lastOrderAt: "2026-05-25",
    preferredCategories: ["Fresh", "Travel size"],
    savedOccasions: ["Graduation", "Corporate"],
    favoriteShopIds: ["shop-citrus-atelier"],
    openTickets: 0,
    notes: "Responds well to fresh office-ready fragrance recommendations.",
    tags: ["Repeat buyer", "Fresh scents"],
  },
  {
    id: "cus-lina",
    name: "Lina M.",
    email: "lina@example.com",
    phone: "+971 52 774 6211",
    city: "Sharjah",
    status: "Needs care",
    segment: "Floral gifts",
    risk: "Medium",
    orders: 3,
    lifetimeValue: 1190,
    avgOrderValue: 397,
    loyaltyPoints: 360,
    lastOrderAt: "2026-05-30",
    preferredCategories: ["Rose", "Mini perfumes", "Gift sets"],
    savedOccasions: ["Birthday", "Wedding"],
    favoriteShopIds: ["shop-rose-vault"],
    openTickets: 1,
    notes: "Awaiting update on a manually captured order.",
    tags: ["Support follow-up", "Gift buyer"],
  },
  {
    id: "cus-hamad",
    name: "Hamad S.",
    email: "hamad@example.com",
    phone: "+971 56 914 8801",
    city: "Ajman",
    status: "Dispute watch",
    segment: "Amber and musk",
    risk: "High",
    orders: 4,
    lifetimeValue: 1810,
    avgOrderValue: 453,
    loyaltyPoints: 510,
    lastOrderAt: "2026-05-24",
    preferredCategories: ["Amber", "Musk", "Bundles"],
    savedOccasions: ["Ramadan"],
    favoriteShopIds: ["shop-musk-room", "shop-oud-lane"],
    openTickets: 1,
    notes: "One active dispute. Keep payout hold until support closes the case.",
    tags: ["Dispute", "COD eligible"],
  },
  {
    id: "cus-nadia",
    name: "Nadia F.",
    email: "nadia@example.com",
    phone: "+971 58 226 1033",
    city: "Dubai",
    status: "Active",
    segment: "Dessert gifting",
    risk: "Low",
    orders: 6,
    lifetimeValue: 2785,
    avgOrderValue: 464,
    loyaltyPoints: 1010,
    lastOrderAt: "2026-05-26",
    preferredCategories: ["Cakes", "Arabic sweets", "Gift boxes"],
    savedOccasions: ["Birthday", "New baby"],
    favoriteShopIds: ["shop-sweet-studio", "shop-la-patisserie"],
    openTickets: 0,
    notes: "Often schedules delivery two days ahead for family occasions.",
    tags: ["Dessert buyer", "Planner"],
  },
];

export const products = [
  {
    id: "prf-001",
    name: "Midnight Oud Reserve",
    shopId: "shop-oud-lane",
    family: "Oud",
    gender: "Unisex",
    notes: ["Cambodian oud", "saffron", "smoked amber"],
    notePyramid: {
      top: ["saffron", "pink pepper"],
      heart: ["Cambodian oud", "rosewood"],
      base: ["smoked amber", "leather musk"],
    },
    sizes: ["50ml", "75ml", "100ml"],
    occasion: ["Evening", "Formal", "Gift"],
    intensity: "Strong",
    longevity: "8-10 hours",
    description: "A deep oud reserve built for evening wear, smoky warmth, and a polished luxury finish.",
    ingredients: ["Alcohol denat.", "Parfum", "Oud accord", "Amber resin", "Saffron extract"],
    howToUse: "Spray on pulse points after moisturizing. Use one to two sprays for indoor evenings.",
    deliveryReturns: "Delivery in 1-3 days. Returns accepted only for unopened perfume boxes.",
    price: 420,
    originalPrice: 490,
    size: "75ml",
    stock: 28,
    rating: 4.9,
    reviews: 86,
    orders: 212,
    verifiedReviews: 79,
    status: "Live",
    tags: ["Best seller", "Evening", "Luxury"],
    collection: "Private Oud Edit",
    releaseType: "Best Seller",
    color: "#7c3d24",
    accent: "#d7b56d",
  },
  {
    id: "prf-002",
    name: "Damask Rose Silk",
    shopId: "shop-rose-vault",
    family: "Floral",
    gender: "Women",
    notes: ["rose absolute", "pink pepper", "white musk"],
    notePyramid: {
      top: ["pink pepper", "pear skin"],
      heart: ["Damask rose", "peony"],
      base: ["white musk", "soft woods"],
    },
    sizes: ["30ml", "50ml", "75ml"],
    occasion: ["Daily", "Gift", "Wedding"],
    intensity: "Moderate",
    longevity: "6-8 hours",
    description: "A silky rose perfume with gentle spice, clean musk, and a feminine gift-ready trail.",
    ingredients: ["Alcohol denat.", "Parfum", "Rose absolute", "White musk accord", "Pink pepper"],
    howToUse: "Spray lightly on wrists and neckline. Layer with unscented lotion for longer wear.",
    deliveryReturns: "Delivery in 1-3 days. Gift sets include exchange support before opening.",
    price: 310,
    originalPrice: 360,
    size: "50ml",
    stock: 16,
    rating: 4.8,
    reviews: 42,
    orders: 118,
    verifiedReviews: 38,
    status: "Needs approval",
    tags: ["Gift pick", "Gift set", "Soft floral"],
    collection: "Rose Weekend",
    releaseType: "New Release",
    color: "#b94d68",
    accent: "#f4b6c4",
  },
  {
    id: "prf-003",
    name: "Citrus Majlis",
    shopId: "shop-citrus-atelier",
    family: "Fresh",
    gender: "Men",
    notes: ["bergamot", "mint leaf", "cedar"],
    notePyramid: {
      top: ["bergamot", "mint leaf"],
      heart: ["green tea", "neroli"],
      base: ["cedar", "clean musk"],
    },
    sizes: ["50ml", "100ml"],
    occasion: ["Daily", "Office", "Travel"],
    intensity: "Moderate",
    longevity: "5-7 hours",
    description: "A clean citrus perfume for warm days, office wear, and polished everyday freshness.",
    ingredients: ["Alcohol denat.", "Parfum", "Bergamot oil", "Cedarwood accord", "Mint extract"],
    howToUse: "Apply two sprays on clean skin. Refresh lightly after long outdoor days.",
    deliveryReturns: "Delivery in 1-3 days. Returns accepted unopened within policy window.",
    price: 255,
    originalPrice: 295,
    size: "100ml",
    stock: 34,
    rating: 4.6,
    reviews: 67,
    orders: 174,
    verifiedReviews: 59,
    status: "Live",
    tags: ["Daily wear", "Office"],
    collection: "Fresh Heat",
    releaseType: "Trending",
    color: "#e29a38",
    accent: "#4aa36f",
  },
  {
    id: "prf-004",
    name: "Velvet Musk No. 8",
    shopId: "shop-musk-room",
    family: "Musk",
    gender: "Unisex",
    notes: ["clean musk", "tonka", "iris"],
    notePyramid: {
      top: ["aldehydes", "iris petal"],
      heart: ["clean musk", "tonka"],
      base: ["skin woods", "powdered amber"],
    },
    sizes: ["30ml", "75ml"],
    occasion: ["Daily", "Office", "Travel"],
    intensity: "Soft",
    longevity: "5-6 hours",
    description: "A soft musk perfume with a quiet skin-scent profile and a limited small-batch feel.",
    ingredients: ["Alcohol denat.", "Parfum", "Clean musk accord", "Tonka bean", "Iris accord"],
    howToUse: "Spray close to skin and clothing edges. Reapply for a softer personal scent bubble.",
    deliveryReturns: "Delivery in 1-3 days. Limited editions are returnable only unopened.",
    price: 280,
    originalPrice: 330,
    size: "75ml",
    stock: 9,
    rating: 4.7,
    reviews: 35,
    orders: 96,
    verifiedReviews: 32,
    status: "Live",
    tags: ["Clean", "Low stock", "Travel size", "Limited edition"],
    collection: "Skin Scent Studio",
    releaseType: "Limited Drop",
    color: "#667085",
    accent: "#d8d1c2",
  },
  {
    id: "prf-005",
    name: "Amber Souk Elixir",
    shopId: "shop-oud-lane",
    family: "Amber",
    gender: "Unisex",
    notes: ["golden amber", "date resin", "vanilla wood"],
    notePyramid: {
      top: ["date resin", "cinnamon"],
      heart: ["golden amber", "benzoin"],
      base: ["vanilla wood", "musk"],
    },
    sizes: ["50ml", "75ml", "100ml"],
    occasion: ["Evening", "Gift", "Formal"],
    intensity: "Strong",
    longevity: "8 hours",
    description: "A warm amber elixir inspired by souk sweetness, resin, vanilla woods, and glowing evening wear.",
    ingredients: ["Alcohol denat.", "Parfum", "Amber accord", "Benzoin resin", "Vanilla wood accord"],
    howToUse: "Spray once on fabric from a safe distance and once on skin for a lasting trail.",
    deliveryReturns: "Delivery in 1-3 days. Returns accepted unopened; exchanges reviewed by support.",
    price: 390,
    originalPrice: 445,
    size: "75ml",
    stock: 21,
    rating: 4.85,
    reviews: 54,
    orders: 143,
    verifiedReviews: 51,
    status: "Live",
    tags: ["Warm", "Compliment getter", "Gift pick"],
    collection: "Golden Souk",
    releaseType: "New Release",
    color: "#c8842f",
    accent: "#315b63",
  },
  {
    id: "prf-006",
    name: "White Tea Horizon",
    shopId: "shop-citrus-atelier",
    family: "Fresh",
    gender: "Women",
    notes: ["white tea", "neroli", "soft woods"],
    notePyramid: {
      top: ["white tea", "lemon leaf"],
      heart: ["neroli", "jasmine water"],
      base: ["soft woods", "white musk"],
    },
    sizes: ["30ml", "50ml"],
    occasion: ["Daily", "Office", "Travel"],
    intensity: "Soft",
    longevity: "4-6 hours",
    description: "A light white tea perfume made for morning routines, travel bags, and clean everyday freshness.",
    ingredients: ["Alcohol denat.", "Parfum", "White tea accord", "Neroli oil", "Soft woods"],
    howToUse: "Spray generously after showering. Ideal for daytime layering and travel refreshes.",
    deliveryReturns: "Delivery in 1-3 days. Mini perfumes follow the standard unopened return policy.",
    price: 235,
    originalPrice: 275,
    size: "50ml",
    stock: 41,
    rating: 4.5,
    reviews: 28,
    orders: 88,
    verifiedReviews: 24,
    status: "Live",
    tags: ["Fresh", "Morning", "Travel size", "New arrival"],
    occasionTags: ["birthday", "graduation"],
    collection: "Tea & Neroli",
    releaseType: "Editor Pick",
    category: "perfume",
    color: "#9ab7b4",
    accent: "#f2d27b",
  },
  {
    id: "prf-007",
    name: "Cocoa Rose Parfum",
    shopId: "shop-sweet-studio",
    category: "perfume",
    family: "Floral",
    gender: "Women",
    notes: ["rose petals", "cocoa blossom", "vanilla musk"],
    notePyramid: {
      top: ["pink pepper", "rose petals"],
      heart: ["cocoa blossom", "peony cream"],
      base: ["vanilla musk", "soft woods"],
    },
    sizes: ["30ml", "50ml"],
    occasion: ["Gift", "Wedding", "Evening"],
    intensity: "Moderate",
    longevity: "6-8 hours",
    description: "A soft floral gourmand perfume created for pairing with chocolate cakes and romantic gift boxes.",
    ingredients: ["Alcohol denat.", "Parfum", "Rose accord", "Cocoa blossom accord", "Vanilla musk"],
    howToUse: "Spray once on pulse points before gifting occasions or evening celebrations.",
    deliveryReturns: "Delivery in 1-3 days. Returns accepted only for unopened perfume boxes.",
    price: 295,
    originalPrice: 345,
    size: "50ml",
    stock: 18,
    rating: 4.8,
    reviews: 31,
    orders: 74,
    verifiedReviews: 29,
    status: "Live",
    tags: ["Gift pick", "Floral gourmand", "Cake pairing"],
    occasionTags: ["birthday", "anniversary", "valentine", "wedding"],
    collection: "Sweet Studio Parfums",
    releaseType: "Gift Pairing",
    color: "#b94d68",
    accent: "#c8842f",
  },
  {
    id: "prf-008",
    name: "Vanilla Amber Souffle",
    shopId: "shop-sweet-studio",
    category: "perfume",
    family: "Amber",
    gender: "Unisex",
    notes: ["vanilla bean", "golden amber", "tonka cream"],
    notePyramid: {
      top: ["vanilla bean", "bergamot zest"],
      heart: ["tonka cream", "orange blossom"],
      base: ["golden amber", "sandalwood"],
    },
    sizes: ["50ml", "75ml"],
    occasion: ["Gift", "Evening", "Daily"],
    intensity: "Moderate",
    longevity: "7-8 hours",
    description: "A warm amber vanilla perfume designed to sit beautifully beside celebration cakes and dessert boxes.",
    ingredients: ["Alcohol denat.", "Parfum", "Vanilla accord", "Amber resin", "Tonka bean"],
    howToUse: "Apply to wrists and neckline. Pair with Sweet Studio desserts for a complete gift ritual.",
    deliveryReturns: "Delivery in 1-3 days. Returns accepted unopened within policy window.",
    price: 335,
    originalPrice: 389,
    size: "75ml",
    stock: 14,
    rating: 4.75,
    reviews: 26,
    orders: 61,
    verifiedReviews: 24,
    status: "Live",
    tags: ["Amber", "Vanilla", "Dessert pairing"],
    occasionTags: ["birthday", "eid", "anniversary", "corporate"],
    collection: "Sweet Studio Parfums",
    releaseType: "New Arrival",
    color: "#c8842f",
    accent: "#f2d27b",
  },

  // ── Cakes ──────────────────────────────────────────────────────
  {
    id: "cke-001",
    category: "cake",
    name: "Chocolate Elegance",
    shopId: "shop-sweet-studio",
    cakeType: "Signature Cake",
    flavors: ["Belgian dark chocolate", "Ganache", "Salted caramel layer"],
    servings: "8–10 servings",
    allergens: ["Gluten", "Dairy", "Eggs"],
    leadTimeDays: 1,
    customMessageAvailable: true,
    price: 189,
    originalPrice: 219,
    size: "",
    stock: 12,
    rating: 4.9,
    reviews: 74,
    orders: 198,
    verifiedReviews: 68,
    status: "Live",
    tags: ["Best seller", "Birthday"],
    occasionTags: ["birthday", "anniversary", "corporate"],
    collection: "Signature Cakes",
    releaseType: "Best Seller",
    color: "#3b1a0d",
    accent: "#c8842f",
    notes: [],
    family: "",
    gender: "",
  },
  {
    id: "cke-002",
    category: "cake",
    name: "Rose Velvet Dream",
    shopId: "shop-sweet-studio",
    cakeType: "Celebration Cake",
    flavors: ["Red velvet", "Rose cream cheese frosting", "Lychee compote"],
    servings: "10–12 servings",
    allergens: ["Gluten", "Dairy", "Eggs"],
    leadTimeDays: 1,
    customMessageAvailable: true,
    price: 225,
    originalPrice: 265,
    size: "",
    stock: 8,
    rating: 4.8,
    reviews: 51,
    orders: 134,
    verifiedReviews: 48,
    status: "Live",
    tags: ["Gift pick", "Wedding", "Floral"],
    occasionTags: ["wedding", "anniversary", "valentine", "birthday"],
    collection: "Celebration Cakes",
    releaseType: "New Arrival",
    color: "#b94d68",
    accent: "#f4b6c4",
    notes: [],
    family: "",
    gender: "",
  },
  {
    id: "cke-003",
    category: "cake",
    name: "Vanilla Cloud",
    shopId: "shop-la-patisserie",
    cakeType: "Classic Cake",
    flavors: ["Madagascar vanilla", "Fresh cream", "Raspberry coulis"],
    servings: "6–8 servings",
    allergens: ["Gluten", "Dairy", "Eggs"],
    leadTimeDays: 1,
    customMessageAvailable: true,
    price: 165,
    originalPrice: 195,
    size: "",
    stock: 15,
    rating: 4.7,
    reviews: 39,
    orders: 105,
    verifiedReviews: 35,
    status: "Live",
    tags: ["Classic", "All occasions"],
    occasionTags: ["birthday", "graduation", "baby_shower"],
    collection: "Classic Collection",
    releaseType: "Trending",
    color: "#f5f0e8",
    accent: "#e9c46a",
    notes: [],
    family: "",
    gender: "",
  },
  {
    id: "cke-004",
    category: "cake",
    name: "Pistachio Royale",
    shopId: "shop-la-patisserie",
    cakeType: "Signature Cake",
    flavors: ["Pistachio sponge", "Rose water cream", "Cardamom honey"],
    servings: "8–10 servings",
    allergens: ["Gluten", "Dairy", "Eggs", "Nuts"],
    leadTimeDays: 2,
    customMessageAvailable: true,
    price: 245,
    originalPrice: 285,
    size: "",
    stock: 6,
    rating: 4.95,
    reviews: 42,
    orders: 89,
    verifiedReviews: 40,
    status: "Live",
    tags: ["Premium", "Arabic", "Limited"],
    occasionTags: ["eid", "ramadan", "wedding", "corporate"],
    collection: "Arabic Heritage",
    releaseType: "Limited Drop",
    color: "#5b7a3f",
    accent: "#d4a840",
    notes: [],
    family: "",
    gender: "",
  },

  // ── Desserts ───────────────────────────────────────────────────
  {
    id: "dss-001",
    category: "dessert",
    name: "Arabic Sweets Collection",
    shopId: "shop-la-patisserie",
    cakeType: "Assorted Box",
    flavors: ["Baklava", "Konafa bites", "Date maamoul", "Rose Turkish delight"],
    servings: "12–15 pieces",
    allergens: ["Gluten", "Dairy", "Nuts"],
    leadTimeDays: 1,
    customMessageAvailable: false,
    price: 98,
    originalPrice: 120,
    size: "500g",
    stock: 30,
    rating: 4.8,
    reviews: 63,
    orders: 210,
    verifiedReviews: 58,
    status: "Live",
    tags: ["Ramadan", "Eid", "Traditional"],
    occasionTags: ["eid", "ramadan", "corporate", "wedding"],
    collection: "Arabic Sweets",
    releaseType: "Seasonal",
    color: "#9c6b2e",
    accent: "#d4a840",
    notes: [],
    family: "",
    gender: "",
  },
  {
    id: "dss-002",
    category: "dessert",
    name: "Chocolate Truffle Box",
    shopId: "shop-sweet-studio",
    cakeType: "Chocolate Box",
    flavors: ["Dark ganache", "Milk hazelnut", "White raspberry"],
    servings: "16 pieces",
    allergens: ["Dairy", "Nuts", "Soy"],
    leadTimeDays: 1,
    customMessageAvailable: false,
    price: 145,
    originalPrice: 169,
    size: "Box of 16",
    stock: 20,
    rating: 4.9,
    reviews: 48,
    orders: 156,
    verifiedReviews: 44,
    status: "Live",
    tags: ["Luxury", "Chocolate", "Gift"],
    occasionTags: ["anniversary", "valentine", "birthday", "corporate"],
    collection: "Chocolate Collection",
    releaseType: "Best Seller",
    color: "#3b1a0d",
    accent: "#c8842f",
    notes: [],
    family: "",
    gender: "",
  },

  // ── Gift Boxes ─────────────────────────────────────────────────
  {
    id: "gft-001",
    category: "gift_box",
    name: "Rose & Velvet Gift Set",
    shopId: "shop-sweet-studio",
    cakeType: "Gift Box",
    flavors: [],
    servings: "",
    allergens: ["Gluten", "Dairy", "Eggs"],
    leadTimeDays: 2,
    customMessageAvailable: true,
    bundledProductIds: ["prf-002", "cke-002"],
    includes: ["Damask Rose Silk 50ml perfume", "Rose Velvet Dream cake", "Luxury gift box", "Handwritten card"],
    price: 499,
    originalPrice: 575,
    size: "",
    stock: 6,
    rating: 4.95,
    reviews: 37,
    orders: 62,
    verifiedReviews: 35,
    status: "Live",
    tags: ["Best gift", "Birthday", "Anniversary"],
    occasionTags: ["birthday", "anniversary", "valentine", "wedding"],
    collection: "Signature Gift Sets",
    releaseType: "Gift Set",
    color: "#b94d68",
    accent: "#f4b6c4",
    notes: [],
    family: "",
    gender: "",
  },
  {
    id: "gft-002",
    category: "gift_box",
    name: "Oud & Chocolate Luxury Box",
    shopId: "shop-sweet-studio",
    cakeType: "Gift Box",
    flavors: [],
    servings: "",
    allergens: ["Dairy", "Nuts", "Soy"],
    leadTimeDays: 2,
    customMessageAvailable: true,
    bundledProductIds: ["prf-001", "dss-002"],
    includes: ["Midnight Oud Reserve 75ml", "Chocolate Truffle Box (16pc)", "Premium black gift box", "Ribbon & card"],
    price: 549,
    originalPrice: 635,
    size: "",
    stock: 8,
    rating: 4.9,
    reviews: 44,
    orders: 71,
    verifiedReviews: 42,
    status: "Live",
    tags: ["Luxury", "Eid", "Premium"],
    occasionTags: ["eid", "ramadan", "anniversary", "corporate"],
    collection: "Luxury Gift Sets",
    releaseType: "Gift Set",
    color: "#7c3d24",
    accent: "#d7b56d",
    notes: [],
    family: "",
    gender: "",
  },
  {
    id: "gft-003",
    category: "gift_box",
    name: "Fresh & Light Celebration Box",
    shopId: "shop-la-patisserie",
    cakeType: "Gift Box",
    flavors: [],
    servings: "",
    allergens: ["Gluten", "Dairy", "Eggs"],
    leadTimeDays: 2,
    customMessageAvailable: true,
    bundledProductIds: ["prf-006", "cke-003"],
    includes: ["White Tea Horizon 50ml", "Vanilla Cloud cake", "Gift box with ribbon", "Personalised card"],
    price: 385,
    originalPrice: 440,
    size: "",
    stock: 10,
    rating: 4.8,
    reviews: 28,
    orders: 43,
    verifiedReviews: 26,
    status: "Live",
    tags: ["Light", "Birthday", "Graduation"],
    occasionTags: ["birthday", "graduation", "baby_shower"],
    collection: "Celebration Gift Sets",
    releaseType: "New Arrival",
    color: "#9ab7b4",
    accent: "#f2d27b",
    notes: [],
    family: "",
    gender: "",
  },
];

export const promotions = [
  {
    id: "promo-gift-sets",
    title: "The art of gifting",
    subtitle: "Perfume and cake paired beautifully in one luxury gift set. Made for every celebration.",
    cta: "Shop gift sets",
    badge: "Gift guide",
    productIds: ["gft-001", "gft-002", "gft-003"],
  },
  {
    id: "promo-eid-edit",
    title: "Eid & Ramadan favourites",
    subtitle: "Warm ouds, Arabic sweets, and luxury gift boxes curated for the season.",
    cta: "Explore the edit",
    badge: "Seasonal",
    productIds: ["prf-001", "prf-005", "dss-001"],
  },
  {
    id: "promo-cakes",
    title: "Cakes for every occasion",
    subtitle: "Artisan signature cakes, celebration cakes, and Arabic heritage desserts.",
    cta: "Shop cakes",
    badge: "New arrivals",
    productIds: ["cke-001", "cke-002", "cke-004"],
  },
];

export const collections = [
  {
    id: "collection-signature",
    title: "Signature Collection",
    description: "Hero scents that define Tuti's warm, premium marketplace style.",
    productIds: ["prf-001", "prf-002", "prf-006"],
  },
  {
    id: "collection-luxury",
    title: "Luxury Collection",
    description: "Richer extrait-style scents with strong verified ratings and high projection.",
    productIds: ["prf-001", "prf-005", "prf-004"],
  },
  {
    id: "collection-oud",
    title: "Oud Collection",
    description: "Deep oud, smoke, saffron, leather, and amber-led perfumes.",
    productIds: ["prf-001", "prf-005"],
  },
  {
    id: "collection-oriental",
    title: "Oriental Collection",
    description: "Warm resins, spices, musk, amber, and evening-ready depth.",
    productIds: ["prf-005", "prf-001", "prf-004"],
  },
  {
    id: "collection-fresh",
    title: "Fresh Collection",
    description: "Citrus, tea, neroli, mint, and clean woods for daily wear.",
    productIds: ["prf-003", "prf-006"],
  },
  {
    id: "collection-floral",
    title: "Floral Collection",
    description: "Rose, iris, soft petals, and polished feminine blends.",
    productIds: ["prf-002", "prf-006"],
  },
  {
    id: "collection-musk",
    title: "Musk Collection",
    description: "Skin scents, white musk, tonka, iris, and quiet luxury.",
    productIds: ["prf-004", "prf-002"],
  },
  {
    id: "collection-seasonal",
    title: "Seasonal Collection",
    description: "Limited drops, gifting edits, and occasion-based perfume stories.",
    productIds: ["prf-004", "prf-005", "prf-002"],
  },
];

export const customerReviews = [
  {
    id: "rev-1001",
    productId: "prf-001",
    customer: "Aisha K.",
    rating: 5,
    title: "Strong oud, very premium finish",
    body: "The opening is bold but settles beautifully. I would buy it again for evening wear.",
    verified: true,
    helpful: 42,
    date: "2026-05-28",
    aspects: { scent: 5, longevity: 5, value: 4 },
  },
  {
    id: "rev-1002",
    productId: "prf-005",
    customer: "Hamad S.",
    rating: 5,
    title: "Warm amber with good projection",
    body: "Lasted through a full workday and the vanilla note is not too sweet.",
    verified: true,
    helpful: 31,
    date: "2026-05-27",
    aspects: { scent: 5, longevity: 4, value: 5 },
  },
  {
    id: "rev-1003",
    productId: "prf-003",
    customer: "Omar R.",
    rating: 4,
    title: "Fresh and easy to wear",
    body: "Great daily perfume. I wanted a little more cedar, but the citrus is clean.",
    verified: true,
    helpful: 18,
    date: "2026-05-25",
    aspects: { scent: 4, longevity: 4, value: 5 },
  },
];

export const paymentLedger = [
  {
    id: "pay-1048",
    orderId: "ORD-9321",
    customer: "Aisha K.",
    shopId: "shop-oud-lane",
    amount: 840,
    commission: 118,
    vendorNet: 722,
    status: "Payout hold",
    capture: "Captured",
    gateway: "Stripe Connect",
    risk: "Low",
    releaseDate: "2026-06-03",
    createdAt: "2026-05-29",
    items: 2,
  },
  {
    id: "pay-1047",
    orderId: "ORD-9318",
    customer: "Omar R.",
    shopId: "shop-citrus-atelier",
    amount: 490,
    commission: 59,
    vendorNet: 431,
    status: "Ready for payout",
    capture: "Captured",
    gateway: "PayTabs Split",
    risk: "Low",
    releaseDate: "2026-05-30",
    createdAt: "2026-05-25",
    items: 2,
  },
  {
    id: "pay-1046",
    orderId: "ORD-9309",
    customer: "Lina M.",
    shopId: "shop-rose-vault",
    amount: 310,
    commission: 40,
    vendorNet: 270,
    status: "Authorization",
    capture: "Manual capture pending",
    gateway: "Stripe Connect",
    risk: "Medium",
    releaseDate: "2026-06-06",
    createdAt: "2026-05-30",
    items: 1,
  },
  {
    id: "pay-1045",
    orderId: "ORD-9301",
    customer: "Hamad S.",
    shopId: "shop-musk-room",
    amount: 560,
    commission: 84,
    vendorNet: 476,
    status: "Dispute hold",
    capture: "Captured",
    gateway: "Tap Payments",
    risk: "High",
    releaseDate: "Paused",
    createdAt: "2026-05-24",
    items: 2,
  },
];

export const payoutQueue = [
  {
    id: "po-5501",
    shopId: "shop-citrus-atelier",
    amount: 431,
    orders: 1,
    status: "Ready",
    method: "Bank transfer",
    releaseDate: "2026-05-30",
  },
  {
    id: "po-5500",
    shopId: "shop-oud-lane",
    amount: 3150,
    orders: 7,
    status: "Scheduled",
    method: "Connected account",
    releaseDate: "2026-06-03",
  },
  {
    id: "po-5498",
    shopId: "shop-musk-room",
    amount: 476,
    orders: 1,
    status: "On hold",
    method: "Bank transfer",
    releaseDate: "Paused",
  },
];

export const orderHistory = [
  {
    orderId: "ORD-9321",
    customerId: "cus-aisha",
    checkoutMode: "account",
    paymentMethod: "card",
    customerName: "Aisha K.",
    customerEmail: "aisha@example.com",
    phone: "+971 50 118 2401",
    items: [
      { productId: "prf-001", productName: "Midnight Oud Reserve", shopId: "shop-oud-lane", price: 420, quantity: 2 },
    ],
    subtotal: 840,
    platformFee: 118,
    vendorNet: 722,
    status: "Shipped",
    paymentStatus: "Payout hold",
    deliveryAddress: "Downtown Dubai, UAE",
    deliveryDate: "2026-05-31",
    deliveryTime: "19:00",
    giftMessage: "For a beautiful evening.",
    notes: "Premium gift wrap requested.",
    shopIds: ["shop-oud-lane"],
    createdAt: "2026-05-29T12:10:00.000Z",
    updatedAt: "2026-05-29T16:40:00.000Z",
  },
  {
    orderId: "ORD-9318",
    customerId: "cus-omar",
    checkoutMode: "account",
    paymentMethod: "card",
    customerName: "Omar R.",
    customerEmail: "omar@example.com",
    phone: "+971 55 302 1940",
    items: [
      { productId: "prf-003", productName: "Citrus Majlis", shopId: "shop-citrus-atelier", price: 255, quantity: 1 },
      { productId: "prf-006", productName: "White Tea Horizon", shopId: "shop-citrus-atelier", price: 235, quantity: 1 },
    ],
    subtotal: 490,
    platformFee: 59,
    vendorNet: 431,
    status: "Delivered",
    paymentStatus: "Ready for payout",
    deliveryAddress: "Al Reem Island, Abu Dhabi",
    deliveryDate: "2026-05-26",
    deliveryTime: "14:30",
    giftMessage: "",
    notes: "Office reception delivery.",
    shopIds: ["shop-citrus-atelier"],
    createdAt: "2026-05-25T09:20:00.000Z",
    updatedAt: "2026-05-26T15:15:00.000Z",
  },
  {
    orderId: "ORD-9309",
    customerId: "cus-lina",
    checkoutMode: "guest",
    paymentMethod: "card",
    customerName: "Lina M.",
    customerEmail: "lina@example.com",
    phone: "+971 52 774 6211",
    items: [
      { productId: "prf-002", productName: "Damask Rose Silk", shopId: "shop-rose-vault", price: 310, quantity: 1 },
    ],
    subtotal: 310,
    platformFee: 40,
    vendorNet: 270,
    status: "Confirmed",
    paymentStatus: "Authorization",
    deliveryAddress: "Al Majaz, Sharjah",
    deliveryDate: "2026-06-01",
    deliveryTime: "18:00",
    giftMessage: "Happy birthday.",
    notes: "Manual capture pending after stock check.",
    shopIds: ["shop-rose-vault"],
    createdAt: "2026-05-30T08:45:00.000Z",
    updatedAt: "2026-05-30T08:45:00.000Z",
  },
  {
    orderId: "ORD-9301",
    customerId: "cus-hamad",
    checkoutMode: "account",
    paymentMethod: "card",
    customerName: "Hamad S.",
    customerEmail: "hamad@example.com",
    phone: "+971 56 914 8801",
    items: [
      { productId: "prf-004", productName: "Velvet Musk No. 8", shopId: "shop-musk-room", price: 280, quantity: 2 },
    ],
    subtotal: 560,
    platformFee: 84,
    vendorNet: 476,
    status: "Processing",
    paymentStatus: "Dispute hold",
    deliveryAddress: "Al Nuaimiya, Ajman",
    deliveryDate: "2026-05-27",
    deliveryTime: "20:00",
    giftMessage: "",
    notes: "Support ticket active. Keep payout paused.",
    shopIds: ["shop-musk-room"],
    createdAt: "2026-05-24T17:05:00.000Z",
    updatedAt: "2026-05-28T10:15:00.000Z",
  },
  {
    orderId: "ORD-9299",
    customerId: "cus-nadia",
    checkoutMode: "account",
    paymentMethod: "cod",
    customerName: "Nadia F.",
    customerEmail: "nadia@example.com",
    phone: "+971 58 226 1033",
    items: [
      { productId: "cke-001", productName: "Chocolate Elegance", shopId: "shop-sweet-studio", price: 260, quantity: 1 },
      { productId: "gft-001", productName: "Rose & Velvet Gift Set", shopId: "shop-sweet-studio", price: 499, quantity: 1 },
    ],
    subtotal: 759,
    platformFee: 106,
    vendorNet: 653,
    status: "Processing",
    paymentStatus: "COD pending",
    deliveryAddress: "Jumeirah, Dubai",
    deliveryDate: "2026-06-02",
    deliveryTime: "16:00",
    giftMessage: "Welcome baby.",
    notes: "Confirm COD collection at delivery.",
    shopIds: ["shop-sweet-studio"],
    createdAt: "2026-05-26T14:10:00.000Z",
    updatedAt: "2026-05-26T14:10:00.000Z",
  },
];

export const roleModel = [
  {
    id: "customer",
    name: "Customer",
    label: "Buyer role",
    permissions: ["Browse catalog", "Buy perfume", "Rate verified orders", "Open returns"],
    boundary: "Cannot edit products, payouts, or shop profiles.",
  },
  {
    id: "seller",
    name: "Seller",
    label: "Seller Central role",
    permissions: ["Upload perfume", "Manage stock", "View orders", "Request payouts"],
    boundary: "Uses a separate seller account area and cannot access admin controls.",
  },
  {
    id: "support",
    name: "Support",
    label: "Tuti service role",
    permissions: ["View orders", "Moderate reviews", "Handle disputes", "Assist customers"],
    boundary: "Cannot release payouts or change commission rules.",
  },
  {
    id: "admin",
    name: "Admin",
    label: "Tuti owner role",
    permissions: ["Approve shops", "Approve products", "Release payouts", "Set policies"],
    boundary: "Full owner operations are kept in the separate admin console.",
  },
];

export const auditEvents = [
  "Manual capture enabled for medium-risk orders above AED 300.",
  "ORD-9301 placed on payout hold after customer dispute.",
  "Payout PO-5501 passed reserve and delivery checks.",
  "Rose Vault submitted trade license for admin review.",
];
